apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itp-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/raghunathrao/argocd-deploy.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: itp-apps

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
