apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 13.1.2
    chart: mongodb
    helm:
      parameters:
        - name: auth.rootPassword
          value: root
        - name: auth.password
          value: secret
        - name: auth.username
          value: mongoadmin
        - name: auth.database
          value: admin
  project: default
