apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 11.8.2
    chart: postgresql
    helm:
      parameters:
        - name: auth.username
          value: root
        - name: auth.password
          value: root
  project: default
