apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-db
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 13.0.2
    chart: mongodb
    helm:
      parameters:
        - name: auth.password
          value: secret
        - name: auth.rootPassword
          value: root
        - name: auth.username
          value: mongoadmin
    project: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
